# ===================================
#  Form Behavior Config
# ===================================

name: smart.catalogue::lang.catalogue.create_category
form: ~/plugins/smart/catalogue/models/category/fields.yaml
modelClass: Smart\Catalogue\Models\Category
defaultRedirect: smart/catalogue/categories

create:
    redirect: smart/catalogue/categories/update/:id
    redirectClose: smart/catalogue/categories

update:
    redirect: smart/catalogue/categories
    redirectClose: smart/catalogue/categories
