# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: smart.catalogue::lang.category.reorder

# Attribute name
nameFrom: name

# Model Class name
modelClass: Smart\Catalogue\Models\Category

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar