# ===================================
#  Form Behavior Config
# ===================================

name: winter.catalogue::lang.catalogue.create_category
form: ~/plugins/smart/catalogue/models/category/fields.yaml
modelClass: Winter\Catalogue\Models\Category
defaultRedirect: winter/catalogue/categories

create:
    redirect: winter/catalogue/categories/update/:id
    redirectClose: winter/catalogue/categories

update:
    redirect: winter/catalogue/categories
    redirectClose: winter/catalogue/categories
