# ===================================
#  Form Behavior Config
# ===================================

name: smart.catalogue::lang.catalogue.create_post
form: ~/plugins/smart/catalogue/models/post/fields.yaml
modelClass: Smart\Catalogue\Models\Post
defaultRedirect: smart/catalogue/posts

create:
    redirect: smart/catalogue/posts/update/:id
    redirectClose: smart/catalogue/posts

update:
    redirect: smart/catalogue/posts
    redirectClose: smart/catalogue/posts
