# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    # Page title
    title: smart.catalogue::lang.posts.import_post

    # Import List Column configuration
    list: $/smart/catalogue/models/postimport/columns.yaml

    # Import Form Field configuration
    form: $/smart/catalogue/models/postimport/fields.yaml

    # Import Model class
    modelClass: Smart\Catalogue\Models\PostImport

    # Redirect when finished
    redirect: smart/catalogue/posts

    # Required permissions
    permissions: smart.catalogue.access_import_export

export:
    # Page title
    title: smart.catalogue::lang.posts.export_post

    # Output file name
    fileName: posts.csv

    # Export List Column configuration
    list: $/smart/catalogue/models/postexport/columns.yaml

    # Export Model class
    modelClass: Smart\Catalogue\Models\PostExport

    # Redirect when finished
    redirect: smart/catalogue/posts

    # Required permissions
    permissions: smart.catalogue.access_import_export
