# ===================================
#  Form Behavior Config
# ===================================

name: winter.catalogue::lang.catalogue.create_post
form: ~/plugins/smart/catalogue/models/post/fields.yaml
modelClass: Winter\Catalogue\Models\Post
defaultRedirect: winter/catalogue/posts

create:
    redirect: winter/catalogue/posts/update/:id
    redirectClose: winter/catalogue/posts

update:
    redirect: winter/catalogue/posts
    redirectClose: winter/catalogue/posts
